### ISSUE TITLE
Game Space Too Big

### ISSUE THREAD

**Issue by valkyrienyanko** [Steviegt6/SnakeGame#1]
The game space is too big for my monitor. When I resize the window, it only resizes the window but the game space still remains large. ![Preview](https://i.gyazo.com/2f66dbfadc05fd7192d592772ae49a47.png)
Notice how the food is somewhere at the bottom, not visible to me.

**Comment by steviegt6** [comment]
Alright, I'll lower the size.

**Comment by steviegt6** [comment]
Issue most likely solved.
Smaller screens may still have trouble viewing changelog text.
